---
# Source: firefly-ca/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: firefly-ca
  labels:
    helm.sh/chart: firefly-ca-v0.1.0-alpha
    app.kubernetes.io/name: firefly-ca
    app.kubernetes.io/instance: venafi-firefly-ca
    app.kubernetes.io/version: "v0.1.0-alpha"
    app.kubernetes.io/managed-by: Helm
---
# Source: firefly-ca/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: issuers.firefly-ca.venafi.com
  labels:
    helm.sh/chart: firefly-ca-v0.1.0-alpha
    app.kubernetes.io/name: firefly-ca
    app.kubernetes.io/instance: venafi-firefly-ca
    app.kubernetes.io/version: "v0.1.0-alpha"
    app.kubernetes.io/managed-by: Helm
spec:
  group: "firefly-ca.venafi.com"
  names:
    kind: Issuer
    plural: issuers
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties: null
---
# Source: firefly-ca/templates/crds.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firefly-ca:approver-firefly-ca-venafi-com
  labels:
    helm.sh/chart: firefly-ca-v0.1.0-alpha
    app.kubernetes.io/name: firefly-ca
    app.kubernetes.io/instance: venafi-firefly-ca
    app.kubernetes.io/version: "v0.1.0-alpha"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - "cert-manager.io"
    resources:
      - signers
    verbs:
      - approve
    resourceNames:
      - "issuers.firefly-ca.venafi.com/*"
---
# Source: firefly-ca/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firefly-ca
  labels:
    helm.sh/chart: firefly-ca-v0.1.0-alpha
    app.kubernetes.io/name: firefly-ca
    app.kubernetes.io/instance: venafi-firefly-ca
    app.kubernetes.io/version: "v0.1.0-alpha"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests/status"]
    verbs: ["update"]
---
# Source: firefly-ca/templates/crds.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: firefly-ca:approver-firefly-ca-venafi-com
  labels:
    helm.sh/chart: firefly-ca-v0.1.0-alpha
    app.kubernetes.io/name: firefly-ca
    app.kubernetes.io/instance: venafi-firefly-ca
    app.kubernetes.io/version: "v0.1.0-alpha"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: firefly-ca:approver-firefly-ca-venafi-com
subjects:
-
  kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
# Source: firefly-ca/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: firefly-ca
  labels:
    helm.sh/chart: firefly-ca-v0.1.0-alpha
    app.kubernetes.io/name: firefly-ca
    app.kubernetes.io/instance: venafi-firefly-ca
    app.kubernetes.io/version: "v0.1.0-alpha"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: firefly-ca
  namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: firefly-ca
  apiGroup: rbac.authorization.k8s.io
---
# Source: firefly-ca/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: firefly-ca:leader-election
  labels:
    helm.sh/chart: firefly-ca-v0.1.0-alpha
    app.kubernetes.io/name: firefly-ca
    app.kubernetes.io/instance: venafi-firefly-ca
    app.kubernetes.io/version: "v0.1.0-alpha"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "update", "create"]
---
# Source: firefly-ca/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: firefly-ca:leader-election
  labels:
    helm.sh/chart: firefly-ca-v0.1.0-alpha
    app.kubernetes.io/name: firefly-ca
    app.kubernetes.io/instance: venafi-firefly-ca
    app.kubernetes.io/version: "v0.1.0-alpha"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: firefly-ca
  namespace: cert-manager
roleRef:
  kind: Role
  name: firefly-ca:leader-election
  apiGroup: rbac.authorization.k8s.io
---
# Source: firefly-ca/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: venafi-firefly-ca
  labels:
    helm.sh/chart: firefly-ca-v0.1.0-alpha
    app.kubernetes.io/name: firefly-ca
    app.kubernetes.io/instance: venafi-firefly-ca
    app.kubernetes.io/version: "v0.1.0-alpha"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: firefly-ca
      app.kubernetes.io/instance: venafi-firefly-ca
  template:
    metadata:
      labels:
        app.kubernetes.io/name: firefly-ca
        app.kubernetes.io/instance: venafi-firefly-ca
    spec:
      serviceAccountName: 'firefly-ca'
      containers:
      - name: firefly-ca
        securityContext:
            capabilities:
              add:
              - IPC_LOCK
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
        image: "public.ecr.aws/venafi-images/firefly-ca:latest"
        imagePullPolicy: IfNotPresent
        command:
        - "firefly-ca"
        - "run"
        - "--disable-mlock=false"
        - "--log-level=2"
        - "--config=/etc/firefly-ca/config.yaml"
        readinessProbe:
          httpGet:
            port: 8080
            path: /readyz
        resources:
            {}
        volumeMounts:
        - name: firefly-ca-config
          mountPath: /etc/firefly-ca
          readOnly: true
        - name: firefly-ca-secrets
          mountPath: /var/run/secrets/firefly-ca.jetstack.io
          readOnly: true
      volumes:
      - name: firefly-ca-config
        configMap:
          name: firefly-ca-config
      - name: firefly-ca-secrets
        secret:
          secretName: firefly-ca-secrets
          optional: true
