bootstrap:
  vaas:
    auth:
      privateKeyFile: /var/run/secrets/firefly.venafi.com/sa-key.pem
      clientID: ${JS_VENAFI_FIREFLY_CLIENT_ID}
    csr:
      instanceNaming: REPLACE_WITH_TIMESTAMP
controller:
  kubeconfigFile: /etc/firefly/kubeconfig.yaml
  cert-manager:
    groupName: "firefly.venafi.com"