apiVersion: jetstack.io/v1alpha1
kind: VenafiConnection
metadata:
  name: application-team-1
  namespace: jetstack-secure
spec:
  tpp:
    url: ${JS_VENAFI_TPP_URL}
    accessToken:
      - serviceAccountToken:
          name: application-team-1
          audiences: ["vault.vault.svc.cluster.local"]
      - hashicorpVaultOAuth:
          authInputType: OIDC
          role: application-team-1
          authPath: /v1/auth/jetstack-secure/login
          url: http://vault.vault.svc.cluster.local:8200
      - hashicorpVaultSecret:
          secretPath: /v1/secret/data/application-team-1/tpp-username-password
          fields: ["username", "password"]
          url: http://vault.vault.svc.cluster.local:8200
      - tppOAuth:
          authInputType: UsernamePassword
          clientId: ${JS_VENAFI_CLIENTID}
          url: ${JS_VENAFI_TPP_URL}
---
apiVersion: jetstack.io/v1alpha1
kind: VenafiConnection
metadata:
  name: application-team-2
  namespace: sandbox
spec:
  tpp:
    url: ${JS_VENAFI_TPP_URL}
    accessToken:
      - serviceAccountToken:
          name: application-team-2
          audiences: ["vault.vault.svc.cluster.local"]
      - hashicorpVaultOAuth:
          authInputType: OIDC
          role: application-team-2
          authPath: /v1/auth/jetstack-secure/login
          url: http://vault.vault.svc.cluster.local:8200
      - hashicorpVaultSecret:
          secretPath: /v1/secret/data/application-team-2/tpp-username-password
          fields: ["username", "password"]
          url: http://vault.vault.svc.cluster.local:8200
      - tppOAuth:
          authInputType: UsernamePassword
          clientId: ${JS_VENAFI_CLIENTID}
          url: ${JS_VENAFI_TPP_URL}
  
