apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-team-1
  namespace: jetstack-secure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-team-2
  namespace: sandbox
---