apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: expiry-eddie.svc.cluster.local
  namespace: sandbox
spec:
  secretName: expiry-eddie.svc.cluster.local
  duration: 2160h
  subject:
    organizations: 
     - Venafi Inc
    organizationalUnits:
     - TLSPK Demo
    localities:
     - Salt Lake City
    provinces:
     - Utah
    countries:
     - US
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - expiry-eddie.svc.cluster.local
  commonName: expiry-eddie.svc.cluster.local
  issuerRef:
    name: "REPLACE_WITH_ISSUER_NAME"
    kind: "VenafiClusterIssuer"
    group: "jetstack.io"
