global:
  imagePullSecrets:
  - name: venafi-jetstack-enterprise-key
controllerManager:
  kubeRbacProxy:
    image:
      repository: ${JS_CONTAINER_REGISTRY}/jetstack-secure-enterprise/kube-rbac-proxy
      tag: v0.13.1
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  manager:
    image:
      repository: ${JS_CONTAINER_REGISTRY}/jetstack-secure-enterprise/venafi-oauth-helper
      tag: v0.3.0
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 20Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
