apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: cert-policy-for-kong-firefly-certs
spec:
  allowed:
    commonName:
      value: "*"
    dnsNames:
      values: ["*"]
    uris:
      values:
      - "spiffe://*"      
      - "kuma://*" 
    isCA: false
    subject:
      organizations:
        values: ["*"]
      countries:
        values: ["*"]
      organizationalUnits:
        values: ["*"]
      localities:
        values: ["*"]
      provinces:
        values: ["*"]
      streetAddresses:
        values: ["*"]
      postalCodes:
        values: ["*"]
    usages:
      - "signing"
      - "digital signature"
      - "client auth"
      - "server auth"
#  plugins:
#    venafi:
#      values:
#        venafiConnectionName: "venafi-*-connection"
#        zone: "application-name\\issuing-template-name"      
  selector:
    issuerRef:
      name: "*"
      kind: "*"
      group: "firefly.venafi.com"
#    namespace:
#       matchNames: 
#       - "sandbox"
#       - "*istio-system"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kong-cyberark-issuer-cluster-role
rules:
  - apiGroups: ["policy.cert-manager.io"]
    resources: ["certificaterequestpolicies"]
    verbs: ["use"]
    # Name of the CertificateRequestPolicies to be used.
    resourceNames: ["cert-policy-for-kong-firefly-certs"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kong-cyberark-issuer-cluster-role-binding
roleRef:
# ClusterRole or Role _must_ be bound to a user for the policy to be considered.
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kong-cyberark-issuer-cluster-role
subjects:
# The users who should be bound to the policies defined.
- kind: ServiceAccount
  name: cert-manager
  namespace: cyberark
- kind: ServiceAccount
  name: kong-mesh-control-plane
  namespace: kong-mesh-system