# Versions based on output of 
# venctl components kubernetes manifest print-versions
export APPROVER_POLICY_ENTERPRISE=v0.20.0
export AWS_PRIVATECA_ISSUER=v1.6.0
export CERT_MANAGER=v1.17.2
export CERT_MANAGER_APPROVER_POLICY=v0.20.0
export CERT_MANAGER_CSI_DRIVER=v0.10.3
export CERT_MANAGER_CSI_DRIVER_SPIFFE=v0.9.1
export CERT_MANAGER_ISTIO_CSR=v0.14.1
export FIREFLY=v1.7.0
export OPENSHIFT_ROUTES=v0.7.0
export TRUST_MANAGER=v0.17.1
export VENAFI_CONNECTION=v0.4.0
export VENAFI_ENHANCED_ISSUER=v0.15.0
export VENAFI_KUBERNETES_AGENT=v1.5.0