make create-certificate-policy
make create-venafi-cloud-privateca-cluster-issuer
#make create-sample-firefly-certs
make seed-data
make mesh-step1
make mesh-step2
make mesh-step3
make mesh-step4
make mesh-step5
make mesh-step6
