# Versions based on output of 
# venctl components kubernetes manifest print-versions
export approver-policy-enterprise :="v0.20.0"
export aws-privateca-issuer :="v1.4.0"
export cert-manager :="v1.16.3"
export cert-manager-approver-policy :="v0.18.0"
export cert-manager-csi-driver :="v0.10.2"
export cert-manager-csi-driver-spiffe :="v0.8.2"
export cert-manager-istio-csr :="v0.14.0"
export firefly :="v1.5.0"
export openshift-routes :="v0.7.0"
export trust-manager :="v0.15.0"
export venafi-connection :="v0.3.1"
export venafi-enhanced-issuer :="v0.15.0"
export venafi-kubernetes-agent :="1.4.0"
