apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: cert-policy-for-voh-helper-user
spec:
  allowed:
    commonName:
      value: "*"
    dnsNames:
      values: ["*"]
    usages:
      - "signing"
      - "digital signature"
      - "server auth"
  plugins:
    tpp:
      values:
        credentialSecretName: vohpolicy-accesstoken
        credentialSecretKey: access-token
        baseURL: ${JS_VENAFI_TPP_URL}
        zone: ${JS_VENAFI_TPP_ZONE_PUBLIC_CA1}
        caBundleConfigMapName: venafi-tpp-ca-bundle
  selector:
    issuerRef:
      name: "voh-venafi-tpp-issuer-user"
      kind: "Issuer"
      group: "cert-manager.io"