apiVersion: v1
kind: Secret
metadata:
  name: vohuser-accesstoken-voh-bootstrap
  annotations:
    voh.jetstack.io/issuer: "voh-venafi-tpp-issuer-user"
  namespace: sandbox #  ⚠ or CLUSTER_RESOURCE_NAMESPACE when using a ClusterIssuer
stringData:
  username: ${JS_VENAFI_TPP_USERNAME}
  password: ${JS_VENAFI_TPP_PASSWORD}