apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: cert-policy-for-isolated-issuer
spec:
  allowed:
    commonName:
      value: "*"
    dnsNames:
      values: ["*"]
    usages:
      - "signing"
      - "digital signature"
      - "server auth"
  plugins:
    venafi:
      values:
        venafiConnectionName: vtpp-connection
        zone: ${JS_VENAFI_TPP_ZONE_PRIVATE_CA1}
  selector:
    issuerRef:
      name: "*"
      kind: "*"
      group: "isolated-issuer.jetstack.io"