apiVersion: jetstack.io/v1alpha1
kind: VenafiConnection
metadata:
  name: venafi-connection
  namespace: cyberark
spec:
  tpp:
    url: ${CYBR_SERVER_URL}
    accessToken:
    - secret:
        name: venafi-tpp-credentials
        fields: ["access-token"]

