apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: pca-issuer-policy-for-ns-sandbox
spec:
  allowed:
    commonName:
      value: "*.svc.cluster.local"
      required: false
    uris:
      values:
      - "spiffe://jetstack-dev/ns/sandbox/sa/*"
      required: true
    dnsNames:
      required: false
      values:
      - "*"
    usages:
      - "signing"
      - "digital signature"
      - "server auth"
    subject:
      organizations:
        values: ["*"]
  selector:
    issuerRef:
      name: "awspca-issuer"
      kind: "AWSPCAIssuer"
      group: "awspca.cert-manager.io"