 # The Venafi TPP URL. Must end with "/vedsdk".
#url: https://foo.env.cloudshare.com/vedsdk

# The CA bundle used to trust the Venafi TPP server when connecting over HTTPS.
# If not enabled, the system root CAs will be used.
caBundle:
  {}
  # configMap:
  #   name: venafi-tpp-ca-bundle
  #   key: ca.crt

# The TPP zone (also called "policy").
#zone: TLS/SSL\\Certificates

# The TPP access token.
#secret:
  #name: access-token
  #key: access-token

image:
  #repository: eu.gcr.io/jetstack-secure-enterprise/cert-discovery-venafi
  #repository: eu.gcr.io/jetstack-secure-enterprise/cert-discovery-venafi-fips
  repository: eu.gcr.io/jetstack-secure-enterprise/cert-discovery-venafi
  pullPolicy: IfNotPresent

  # When no tag is given, the apiVersion is used instead.
  # tag: v0.1.0

# The images in this project are stored in a private GCR registry. You will need
# to ask for the JSON key to access the registry, and store it in a Secret with
# the command:
#
#   kubectl create secret docker-registry jetstack-secure-enterprise -n cert-discovery-venafi \
#     --docker-server=https://gcr.io \
#     --docker-username=_json_key \
#     --docker-email=unused@example.com \
#     --docker-password="$(cat json-key.json)"
#
# For for information, see:
# http://docs.heptio.com/content/private-registries/pr-gcr.html
imagePullSecrets:
 - name: venafi-jetstack-enterprise-key

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 20Mi

replicas: 1

# The /metrics endpoint is reachable through the kube-rbac-proxy on port 8443.
# You need to bind your Prometheus service account to the ClusterRole
# cert-discovery-venafi-metrics-reader.
# See: https://book.kubebuilder.io/reference/metrics.html#protecting-the-metrics
metrics:
  enabled: true
  service:
    type: ClusterIP
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.4.1