# Versions based on output of 
# venctl components kubernetes manifest print-versions
export approver-policy-enterprise :="v0.20.0"
export aws-privateca-issuer :="v1.4.1"
export cert-manager :="v1.17.1"
export cert-manager-approver-policy :="v0.19.0"
export cert-manager-csi-driver :="v0.10.2"
export cert-manager-csi-driver-spiffe :="v0.8.2"
export cert-manager-istio-csr :="v0.14.0"
export firefly :="v1.6.0"
export openshift-routes :="v0.7.0"
export trust-manager :="v0.16.0"
export venafi-connection :="v0.4.0"
export venafi-enhanced-issuer :="v0.15.0"
export venafi-kubernetes-agent :="v1.4.1"
