apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ghost-rider.svc.cluster.local
  namespace: sandbox
spec:
  secretName: ghost-rider.svc.cluster.local
  duration: 2184h
  subject:
    organizations: 
     - CyberArk Inc
    organizationalUnits:
     - MIS Demo
    localities:
     - Newton
    provinces:
     - MA
    countries:
     - US
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - ghost-rider.svc.cluster.local
  commonName: ghost-rider.svc.cluster.local
  issuerRef:
    name: "REPLACE_WITH_ISSUER_NAME"
    kind: "VenafiClusterIssuer"
    group: "jetstack.io"
