---
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups: []
#- jetstack-secure:jetstack-privileged
#- system:authenticated
kind: SecurityContextConstraints
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubernetes.io/description: restricted denies access to all host features and requires
      pods to be run with a UID, and SELinux context that are allocated to the namespace.  This
      is the most restrictive SCC and it is used by default for authenticated users.
    release.openshift.io/create-only: "true"
  generation: 1
  name: jetstack-privileged
priority: null
readOnlyRootFilesystem: false
allowHostDirVolumePlugin: true
runAsNonRoot: true
requiredDropCapabilities:
- ALL
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
seccompProfiles:    
- runtime/default
users: 
- system:serviceaccount:jetstack-secure:cert-manager
- system:serviceaccount:jetstack-secure:cert-manager-approver-policy
- system:serviceaccount:jetstack-secure:cert-manager-cainjector
- system:serviceaccount:jetstack-secure:cert-manager-webhook
- system:serviceaccount:jetstack-secure:trust-manager
- system:serviceaccount:jetstack-secure:venafi-enhanced-issuer-controller-manager
- system:serviceaccount:jetstack-secure:cert-manager-csi-driver
- system:serviceaccount:jetstack-secure:cert-manager-csi-driver-spiffe-approver
- system:serviceaccount:jetstack-secure:cert-manager-csi-driver-spiffe
- system:serviceaccount:jetstack-secure:cert-sync-to-venafi-cert-discovery-venafi-sa
- system:serviceaccount:jetstack-secure:venafi-enhanced-issuer
- system:serviceaccount:jetstack-secure:js-operator-cainjector
- system:serviceaccount:jetstack-secure:js-operator-operator
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
- tmp