apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: sandbox
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: sandbox
spec:
  secretName: test-cert
  commonName: test-cert
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

