apiVersion: v1
kind: Secret
metadata:
  name: vohpolicy-accesstoken-voh-bootstrap
  annotations:
    voh.jetstack.io/issuer: "policy-tpp-issuer-user"
  namespace: jetstack-secure #  ⚠ or CLUSTER_RESOURCE_NAMESPACE when using a ClusterIssuer
stringData:
  username: ${JS_VENAFI_TPP_USERNAME}
  password: ${JS_VENAFI_TPP_PASSWORD}