apiVersion: v1
kind: ServiceAccount
metadata:
  name: spiffe-redis-sa
  namespace: sandbox
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spiffe-redis-server-app
  namespace: sandbox
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["create"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spiffe-redis-server-app
  namespace: sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spiffe-redis-server-app
subjects:
- kind: ServiceAccount
  name: spiffe-redis-sa
  namespace: sandbox
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spiffe-redis-server-config
  namespace: sandbox
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
    port 0
    tls-port 6379
    tls-cert-file /redis-server-tls/certs/tls.crt
    tls-key-file /redis-server-tls/certs/tls.key
    tls-ca-cert-file /redis-server-tls/certs/ca.crt
    tls-ca-cert-dir /etc/ssl/certs
    tls-auth-clients yes
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiffe-redis-server-app
  namespace: sandbox
  labels:
    app: spiffe-redis-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spiffe-redis-server-app
  template:
    metadata:
      labels:
        app: spiffe-redis-server-app
    spec:
      serviceAccountName: spiffe-redis-sa
      containers:
      - name: redis
        image: redis:alpine
        command:
          - redis-server
          - "/redis-server/redis.conf"    
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-server-data
          name: data
        - mountPath: /redis-server
          name: config
        - mountPath: /redis-server-tls/certs
          name: spiffe-redis-server-cert
      volumes:
        - name: data
          emptyDir: {}
        - name: spiffe-redis-server-cert
          csi:
            driver: spiffe.csi.cert-manager.io
            readOnly: true
        - name: config
          configMap:
            name: spiffe-redis-server-config
            items:
            - key: redis-config
              path: redis.conf

---
apiVersion: v1
kind: Service
metadata:
  name: spiffe-redis-server
  namespace: sandbox
  labels:
    app: spiffe-redis-server-app
spec:
  type: ClusterIP
  selector:
    app: spiffe-redis-server-app
  ports:
  - name: spiffe-redis-server-app
    port: 6379
    targetPort: 6379