apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-app-sa
  namespace: sandbox
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spiffe-client-app
  namespace: sandbox
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["create"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spiffe-client-app
  namespace: sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spiffe-client-app
subjects:
- kind: ServiceAccount
  name: client-app-sa
  namespace: sandbox
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiffe-client-app
  namespace: sandbox
  labels:
    app: spiffe-client-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spiffe-client-app
  template:
    metadata:
      labels:
        app: spiffe-client-app
    spec:
      serviceAccountName: client-app-sa
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /spiffe-client-tls/certs
          name: spiffe-client-certs
      volumes:
        - name: spiffe-client-certs
          csi:
            driver: spiffe.csi.cert-manager.io
            readOnly: true

#redis-cli -h spiffe-redis-server.sandbox.svc.cluster.local -p 6379 --tls --cacert /spiffe-client-tls/certs/ca.crt --cert /spiffe-client-tls/certs/tls.crt --key /spiffe-client-tls/certs/tls.key ping
