---
apiVersion: v1
kind: Secret
metadata:
  name: vtpp-vei-creds-secret
  namespace: jetstack-secure
stringData:
  username: ${JS_VENAFI_TPP_USERNAME}
  password: ${JS_VENAFI_TPP_PASSWORD}
  access-token: ${JS_VENAFI_TPP_ACCESS_TOKEN}
---
apiVersion: v1
kind: Secret
metadata:
  name: vtpp-vei-creds-secret
  namespace: sandbox
stringData:
  username: ${JS_VENAFI_TPP_USERNAME}
  password: ${JS_VENAFI_TPP_PASSWORD}
  access-token: ${JS_VENAFI_TPP_ACCESS_TOKEN}
---
