---
apiVersion: jetstack.io/v1alpha1
kind: VenafiClusterIssuer
metadata:
  name: vtpp-cluster-issuer
spec:
  venafiConnectionName: vtpp-cluster-connection
  zone: ${JS_VENAFI_TPP_ZONE_PUBLIC_CA1}
---
