# Default values for jetstack-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- default replicas, do not scale up
replicaCount: 1

image:
  # -- Default to Open Source image repository
  repository: registry.venafi.cloud/venafi-agent/venafi-agent
  # -- Defaults to only pull if not already present
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion
  tag: "v0.1.48"

# -- Specify image pull credentials if using a private registry
# example: - name: my-pull-secret
imagePullSecrets: []

# -- Helm default setting to override release name, usually leave blank.
nameOverride: ""

# -- Helm default setting, use this to shorten the full install name.
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations YAML to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If blank and `serviceAccount.create` is true, a name is generated using the fullname template of the release.
  name: ""

# -- Additional YAML annotations to add the the pod.
podAnnotations: {}

# -- Optional Pod (all containers) `SecurityContext` options, see https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod.
podSecurityContext: {}
  # runAsUser: 1000
  # runAsGroup: 3000
  # fsGroup: 2000

# Use these variables to configure the HTTP_PROXY environment variables.

# Configures the HTTP_PROXY environment variable where a HTTP proxy is required.
# +docs:property
# http_proxy: "http://proxy:8080"

# Configures the HTTPS_PROXY environment variable where a HTTP proxy is required.
# +docs:property
# https_proxy: "https://proxy:8080"

# Configures the NO_PROXY environment variable where a HTTP proxy is required,
# but certain domains should be excluded.
# +docs:property
# no_proxy: 127.0.0.1,localhost

# -- Add Container specific SecurityContext settings to the container. Takes precedence over `podSecurityContext` when set. See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# -- Set custom resourcing settings for the pod. You may not want this if you intend to use a Vertical Pod Autoscaler.
resources:
  requests:
    memory: 200Mi
    cpu: 200m
  limits:
    memory: 500Mi
    cpu: 500m

# -- Embed YAML for nodeSelector settings, see https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/
nodeSelector: {}

# -- Embed YAML for toleration settings, see https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations: []

# -- Embed YAML for Node affinity settings, see https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/.
affinity: {}

# -- Specify the command to run overriding default binary.
command: []

# -- Specify additional arguments to pass to the agent binary.
# For example `["--strict", "--oneshot"]`
extraArgs: []

# -- Authentication details for the Venafi Kubernetes Agent
authentication:
  # -- Name of the secret containing the private key
  secretName: agent-credentials
  # -- Key name in the referenced secret
  secretKey: "privatekey.pem"

# -- Configuration section for the Venafi Kubernetes Agent itself
config:
  # -- Overrides the server if using a proxy in your environment
  # For the EU variant use: https://api.venafi.eu/
  server: "https://api.venafi.cloud/"
  # -- The client-id returned from the Venafi Control Plane
  #clientId: "f0d50e0c-191e-11ef-9d83-662a16fdf4c2"
  clientId: 
  # -- Send data back to the platform every minute unless changed
  period: "0h1m0s"
  # -- Name for the cluster resource if it needs to be created in Venafi Control Plane
  clusterName: 
  # -- Description for the cluster resource if it needs to be created in Venafi Control Plane
  clusterDescription: 

  # -- Specify ConfigMap details to load config from an existing resource.
  # This should be blank by default unless you have you own config.
  configmap:
    name:
    key:

# -- Configure a PodDisruptionBudget for the agent's Deployment. If running with multiple
# replicas, consider setting podDisruptionBudget.enabled to true.
podDisruptionBudget:
  # -- Enable or disable the PodDisruptionBudget resource, which helps prevent downtime
  # during voluntary disruptions such as during a Node upgrade.
  enabled: false

  # -- Configure the minimum available pods for disruptions. Can either be set to
  # an integer (e.g. 1) or a percentage value (e.g. 25%).
  # Cannot be used if `maxUnavailable` is set.
  # minAvailable: 1

  # -- Configure the maximum unavailable pods for disruptions. Can either be set to
  # an integer (e.g. 1) or a percentage value (e.g. 25%).
  # Cannot be used if `minAvailable` is set.
  # maxUnavailable: 1

