global:
  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets:
  - name: venafi-jetstack-enterprise-key

installCRDs: true
extraArgs:
  # Use this flag to enabled or disable arbitrary controllers, for example, disable the CertificiateRequests approver
  - --controllers=*,-certificaterequests-approver

image:
  #repository: quay.io/jetstack/cert-manager-controller
  #repository: eu.gcr.io/jetstack-secure-enterprise/cert-manager-controller
  #repository: eu.gcr.io/jetstack-secure-enterprise/cert-manager-controller-fips
  repository: ${JS_CONTAINER_REGISTRY}/jetstack-secure-enterprise/cert-manager-controller
  pullPolicy: IfNotPresent
  tag: v1.10.0

webhook:  
  image:
    #repository: quay.io/jetstack/cert-manager-webhook
    #repository: eu.gcr.io/jetstack-secure-enterprise/cert-manager-webhook
    #repository: eu.gcr.io/jetstack-secure-enterprise/cert-manager-webhook-fips
    repository: ${JS_CONTAINER_REGISTRY}/jetstack-secure-enterprise/cert-manager-webhook
    pullPolicy: IfNotPresent
    tag: v1.10.0
  
cainjector:
  image:
    #repository: quay.io/jetstack/cert-manager-cainjector
    #repository: eu.gcr.io/jetstack-secure-enterprise/cert-manager-cainjector
    #repository: eu.gcr.io/jetstack-secure-enterprise/cert-manager-cainjector-fips
    repository: ${JS_CONTAINER_REGISTRY}/jetstack-secure-enterprise/cert-manager-cainjector
    pullPolicy: IfNotPresent
    tag: v1.10.0
    
startupapicheck:
  image:
    #repository: quay.io/jetstack/cert-manager-ctl
    #repository: eu.gcr.io/jetstack-secure-enterprise/cert-manager-ctl
    #repository: eu.gcr.io/jetstack-secure-enterprise/cert-manager-ctl-fips
    repository: ${JS_CONTAINER_REGISTRY}/jetstack-secure-enterprise/cert-manager-ctl
    pullPolicy: IfNotPresent
    tag: v1.10.0
    