---
apiVersion: v1
kind: Secret
metadata:
  name: venafi-credentials
  namespace: jetstack-secure
stringData:
  username: ${JS_VENAFI_TPP_USERNAME}
  password: ${JS_VENAFI_TPP_PASSWORD}
  access-token: ${JS_VENAFI_TPP_ACCESS_TOKEN}
  vaas-api-key: ${JS_VENAFI_CLOUD_API_KEY}
---