---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-issuer.vttp.vei.${JS_JETSTACKER_DOMAIN_NAME}
  namespace: sandbox
spec:
  secretName: sample-issuer.vttp.vei.${JS_JETSTACKER_DOMAIN_NAME}
  duration: 2160h
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - sample-issuer.vttp.vei.${JS_JETSTACKER_DOMAIN_NAME}
  commonName: sample-issuer.vttp.vei.${JS_JETSTACKER_DOMAIN_NAME}
  issuerRef:
    name: "vtpp-sandbox-issuer"
    kind: "VenafiIssuer"
    group: "jetstack.io"
---
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-ci.vttp.vei.${JS_JETSTACKER_DOMAIN_NAME}
  namespace: sandbox
spec:
  secretName: sample-ci-issuer.vttp.vei.${JS_JETSTACKER_DOMAIN_NAME}
  duration: 2160h
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - sample-ci.vttp.vei.${JS_JETSTACKER_DOMAIN_NAME}
  commonName: si-issuer.vttp.vei.${JS_JETSTACKER_DOMAIN_NAME}
  issuerRef:
    name: "vtpp-cluster-issuer"
    kind: "VenafiClusterIssuer"
    group: "jetstack.io"
---