global:
  imagePullSecrets:
  - name: ${JS_DOCKER_REGISTRY_SECRET}
controllerManager:
  kubeRbacProxy:
    image:
      repository: ${JS_CONTAINER_REGISTRY}/kube-rbac-proxy
      tag: ${JS_KUBE_RBAC_PROXY_IMAGE_VERSION}
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  manager:
    image:
      repository: ${JS_CONTAINER_REGISTRY}/venafi-enhanced-issuer
      tag: ${JS_VENAFI_ENHANCED_ISSUER_IMAGE_VERSION}
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    # The trustedCaBundles allows you to specify additional CA certificate
    # bundles that will be mounted to /etc/ssl/certs/. Note that Mozilla's CA
    # certificates are present in the image by default at
    # /etc/ssl/certs/ca-certificates.crt, and cannot be disabled.
    trustedCaBundles:
     - configMapName: venafi-tpp-ca-bundle
       configMapKey: ca.crt
    # - configMapName: ca-cert-vault
    #   configMapKey: ca.crt
  replicas: 1
kubernetesClusterDomain: cluster.local
managerConfig:
  controllerManagerConfigYaml:
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: true
      resourceName: f8d4bf2e.jetstack.io
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
metricsService:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  type: ClusterIP
