apiVersion: v1
kind: Secret
metadata:
  name: vtpp-access-token
  namespace: sandbox
stringData:
  access-token: ${JS_VENAFI_TPP_ACCESS_TOKEN}

---

apiVersion: jetstack.io/v1alpha1
kind: VenafiIssuer
metadata:
  name: vtpp-sandbox-issuer
  namespace: sandbox
spec:
  tpp:
    policyDN: ${JS_VENAFI_TPP_ZONE_PUBLIC_CA1}
    url: ${JS_VENAFI_TPP_URL}
    accessToken:
    - secret:
        name: vtpp-access-token
        fields: ["access-token"]


  