apiVersion: jetstack.io/v1alpha1
kind: VenafiConnection
metadata:
  name: vtpp-connection-access-token
  namespace: sandbox
spec:
  tpp:
    url: ${JS_VENAFI_TPP_URL}
    accessToken:
    - secret:
        name: vtpp-vei-access-token
        fields: ["access-token"]

