---
apiVersion: jetstack.io/v1alpha1
kind: VenafiIssuer
metadata:
  name: vtpp-enhanced-issuer
  namespace: sandbox
spec:
  venafiConnectionName: vtpp-connection-access-token
  zone: ${JS_VENAFI_TPP_ZONE_PUBLIC_CA1}
---