apiVersion: v1
kind: Secret
metadata:
  name: vtpp-vei-access-token
  namespace: sandbox
stringData:
  access-token: ${JS_VENAFI_TPP_ACCESS_TOKEN}
---
apiVersion: jetstack.io/v1alpha1
kind: VenafiIssuer
metadata:
  name: vtpp-enhanced-issuer
  namespace: sandbox
spec:
  tpp:
    policyDN: ${JS_VENAFI_TPP_ZONE_PUBLIC_CA1}
    url: ${JS_VENAFI_TPP_URL}
    accessToken:
    - secret:
        name: vtpp-vei-access-token
        fields: ["access-token"]
---
apiVersion: v1
kind: Secret
metadata:
  name: vtpp-vei-user-pass
  namespace: jetstack-secure
stringData:
  username: ${JS_VENAFI_TPP_USERNAME}
  password: ${JS_VENAFI_TPP_PASSWORD}

---
apiVersion: jetstack.io/v1alpha1
kind: VenafiClusterIssuer
metadata:
  name: vtpp-enhanced-clusterissuer
spec:
  tpp:
    policyDN: ${JS_VENAFI_TPP_ZONE_PUBLIC_CA1}
    url: ${JS_VENAFI_TPP_URL}
    accessToken:
      - secret:
          name: vtpp-vei-user-pass
          fields: ["username", "password"]
      - tppOAuth:
          authInputType: UsernamePassword
          clientId: "cert-manager.io"
          url: ${JS_VENAFI_TPP_URL}



  