apiVersion: v1
kind: Secret
metadata:
  name: vohauth-accesstoken-voh-bootstrap
  annotations:
    voh.jetstack.io/issuer: "voh-venafi-tpp-issuer-auth" # FOR CLUSTER ISSUER voh.jetstack.io/cluster-issuer: "clusterissuer-name"
  namespace: sandbox #  ⚠ or CLUSTER_RESOURCE_NAMESPACE when using a ClusterIssuer
stringData:
  refresh-token: ${JS_VENAFI_TPP_REFRESH_TOKEN}
  refresh-token-expires: ${JS_VENAFI_TPP_REFRESH_TOKEN_EXPIRY}