apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jetstack-istio-ca.istio-system.svc.cluster.local
  namespace: istio-system
spec:
  isCA: true
  duration: 2160h # 90d
  secretName: jetstack-istio-ca.istio-system.svc.cluster.local
  privateKey:
    rotationPolicy: Always
  commonName: jetstack-istio-ca.istio-system.svc.cluster.local
  subject:
    organizations:
    - cluster.local
    - cert-manager
    - jetstack-dev
  issuerRef:
    name: vtpp-intermediate-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: jetstack-istio-ca
  namespace: istio-system
spec:
  ca:
    secretName: jetstack-istio-ca.istio-system.svc.cluster.local
