apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: storefront-vtpp.${JS_JETSTACKER_DOMAIN_NAME}
  namespace: istio-system
spec:
  secretName: storefront-vtpp.${JS_JETSTACKER_DOMAIN_NAME}
  duration: 72h
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - storefront-vtpp.${JS_JETSTACKER_DOMAIN_NAME}
  commonName: storefront-vtpp.${JS_JETSTACKER_DOMAIN_NAME}
  issuerRef:
    name: vtpp-public-issuer
    kind: VenafiClusterIssuer
    group: jetstack.io
--- 