apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: istio-system
stringData:
  token: root
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: jetstack-istio-ca
  namespace: istio-system
spec:
  vault:
    path: jetstack-demo-mesh-ca/sign/jetstack-secure-istio-csr
    server: http://vault.vault.svc.cluster.local:8200
    auth:
      tokenSecretRef:
          name: vault-token
          key: token
