apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-policy:cert-policy-for-apps-in-sandbox
  namespace: sandbox
rules:
  - apiGroups: ["policy.cert-manager.io"]
    resources: ["certificaterequestpolicies"]
    verbs: ["use"]
    # Name of the CertificateRequestPolicies to be used.
    resourceNames: ["cert-policy-for-apps-in-sandbox"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-policy:cert-policy-for-apps-in-sandbox
  namespace: sandbox
roleRef:
# ClusterRole or Role _must_ be bound to a user for the policy to be considered.
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-policy:cert-policy-for-apps-in-sandbox
subjects:
# The users who should be bound to the policies defined.
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
