# Versions based on output of 
# venctl components kubernetes manifest print-versions
export APPROVER_POLICY_ENTERPRISE=v0.22.0
export AWS_PRIVATECA_ISSUER=v1.7.0
export CERT_MANAGER=v1.19.1
export CERT_MANAGER_APPROVER_POLICY=v0.22.2
export CERT_MANAGER_CSI_DRIVER=v0.11.1
export CERT_MANAGER_CSI_DRIVER_SPIFFE=v0.10.1
export CERT_MANAGER_ISTIO_CSR=v0.14.3
export FIREFLY=v1.9.3
export OPENSHIFT_ROUTES=v0.8.3
export TRUST_MANAGER=v0.20.2
export VENAFI_CONNECTION=v0.5.1
export VENAFI_ENHANCED_ISSUER=v0.17.2
export VENAFI_KUBERNETES_AGENT=v1.7.1