apiVersion: v1
stringData:
  AWS_REGION: ${JS_AWS_REGION}
  AWS_ACCESS_KEY_ID: ${JS_AWS_PCA_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${JS_AWS_PCA_SECRET_ACCESS_KEY}
kind: Secret
metadata:
  name: aws-pca-secret
  namespace: sandbox
type: Opaque
