bootstrap:
  remote:
  # first, we need to configure our CSR for our intermediate
    csr:
      duration: 48h
      commonName: isolated-issuer-getting-started
      privateKey:
        algorithm: ECDSA
        size: 256
      subject:
        organizations:
        - example.com
    # next, we need to specify the issuer we'll use to generate our intermediate
    # this part will change depending on how you're going to bootstrap your cert
    cert-manager:
      issuerName: isolated-issuer-root-ca-issuer
      issuerKind: Issuer
      namespace: isolated-issuer-test
signer:
  # we use the simplest, in-memory signer, which requires no further configuration
  inMemory: true
controller:
  # finally, we configure our controller. note that the groupName must match the
  # one which was defined in the CRD and RBAC role
  cert-manager:
    groupName: "isolated-issuer.jetstack.io"
    caFile: docs/getting_started/root.pem
