apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: java-server-app-cert
  namespace: sample-apps
spec:
  secretName: java-server-truststore
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - digital signature
    - server auth
  commonName: javaserver.svc.cluster.local
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: password-key
        name: jks-password-secret
    pkcs12:
      create: true
      passwordSecretRef:
        key: password-key
        name: jks-password-secret
  issuerRef:
    name: "vtpp-enhanced-clusterissuer"
    kind: "VenafiClusterIssuer"
    group: "jetstack.io"
