---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coffee.${JS_JETSTACKER_DOMAIN_NAME}
  namespace: sandbox
spec:
  secretName: coffee.${JS_JETSTACKER_DOMAIN_NAME}
  duration: 2160h
  renewBefore: 1h
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - coffee.${JS_JETSTACKER_DOMAIN_NAME}
  commonName: coffee.${JS_JETSTACKER_DOMAIN_NAME}
  issuerRef:
    name: "vtpp-enhanced-clusterissuer"
    kind: "VenafiClusterIssuer"
    group: "jetstack.io"
---
