---
# create role that allows creating sa tokens for 'sandbox'
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-secret-role-for-venafi-connection
  namespace: jetstack-secure
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  resourceNames: ["venafi-credentials"]
---
# link the controller's service account to the 'create-tokens-for-vault-sa' role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secret-role-for-venafi-connection
  namespace: jetstack-secure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-secret-role-for-venafi-connection
subjects:
- kind: ServiceAccount
  name: venafi-connection
  namespace: jetstack-secure
