apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: istio-ca-root-cert
spec:
  sources:
  # Include a bundle of publicly trusted certificates which can be
  # used to validate most TLS certificates on the internet, such as
  # those issued by Let's Encrypt, Google, Amazon and others.
  #- useDefaultCAs: true  
  - secret:
      name: "venafi-trust-anchor"
      key: "root-cert.pem"
  target:
    # Data synced to the ConfigMap `my-org.com` or your private CA root at the key `ca.crt` in
    # every namespace based on the sources above.
    configMap:
      key: "root-cert.pem"
    namespaceSelector:
      matchLabels:
         issuer: "venafi-firefly"
