---
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: cert-policy-for-vsat
spec:
  allowed:
    isCA: true
    commonName:
      value: "*"
    dnsNames:
      values: ["*"]
    usages:
      - "digital signature"
      - "server auth"
  selector:
    issuerRef:
      name: "vsat-certs-selfsigned"
      kind: "ClusterIssuer"
      group: "cert-manager.io"
---
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: cert-policy-for-vsat-ca
spec:
  allowed:
    commonName:
      value: "*"
    dnsNames:
      values: ["*"]
    usages:
      - "digital signature"
      - key encipherment
      - server auth
      - client auth
  selector:
    issuerRef:
      name: "vsat-certs-ca"
      kind: "ClusterIssuer"
      group: "cert-manager.io"
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-policy-role-for-vsat
rules:
  - apiGroups: ["policy.cert-manager.io"]
    resources: ["certificaterequestpolicies"]
    verbs: ["use"]
    # Name of the CertificateRequestPolicies to be used.
    resourceNames: ["cert-policy-for-vsat","cert-policy-for-vsat-ca"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-policy-role-for-vsat
roleRef:
# ClusterRole or Role _must_ be bound to a user for the policy to be considered.
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-policy-role-for-vsat
subjects:
# The users who should be bound to the policies defined.
- kind: ServiceAccount
  name: cert-manager
  namespace: jetstack-secure