apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert1-from-remote-isolated-issuer
  namespace: venafi-tpp
spec:
  isCA: false
  commonName: cert1-from-remote-isolated-issuer
  privateKey:
    rotationPolicy: Always
  duration: 1h
  secretName: cert1-from-remote-isolated-issuer
  issuerRef:
    name: "isolated-issuer-on-vm1"
    group: "isolated-issuer.jetstack.io"
  dnsNames:
  - foo.example.com
  - bar.example.com

--- 

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert2-from-remote-isolated-issuer
  namespace: venafi-tpp
spec:
  isCA: false
  commonName: cert2-from-remote-isolated-issuer
  privateKey:
    rotationPolicy: Always
  duration: 1h
  secretName: cert2-from-remote-isolated-issuer
  issuerRef:
    name: "isolated-issuer-on-vm1"
    group: "isolated-issuer.jetstack.io"
  dnsNames:
  - foo.example.com
  - bar.example.com

--- 

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert3-from-remote-isolated-issuer
  namespace: venafi-tpp
spec:
  isCA: false
  commonName: cert3-from-remote-isolated-issuer
  privateKey:
    rotationPolicy: Always
  duration: 1h
  secretName: cert3-from-remote-isolated-issuer
  issuerRef:
    name: "isolated-issuer-on-vm1"
    group: "isolated-issuer.jetstack.io"
  dnsNames:
  - foo.example.com
  - bar.example.com

