apiVersion: cert-manager.skyscanner.net/v1alpha1
kind: KMSIssuer
metadata:
  name: kms-issuer
  namespace: sandbox
spec:
  keyId: alias/jetstack-secure-kms-key # The KMS key id or alias
  commonName: Jetstack Secure Demo Root CA # The common name for the root certificate
  duration: 8760h # 1 years